apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rest2kafka-demo-deploy
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      parameters:
        - name: cluster.domain
          value: apps.cluster-hnlkm.hnlkm.gcp.redhatworkshops.io
        - name: demo.namespace
          value: appdev-streams
        - name: strimzi.subscriptionName
          value: strimzi-operator
        - name: strimzi.operatorGroupName
          value: strimzi-operatorgroup
        - name: datagrid.subscriptionName
          value: datagrid-operator
        - name: datagrid.operatorGroupName
          value: datagrid-operatorgroup     
    path: rest2kafka-demo-deploy
    repoURL: 'https://github.com/sgutierr/rest2kafka.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m
      limit: 10
    syncOptions:
      - CreateNamespace=true