apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: correlationid-consumer-applications-cache
  namespace: {{ .Values.demo.namespaceName }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"  
spec:
  clusterName: example-infinispan
  name: correlationid-cache
  template: <replicated-cache mode="SYNC" statistics="true"><encoding media-type="application/x-protostream"/><expiration lifespan="300000" max-idle="-1"/><memory max-count="1000000" when-full="REMOVE"/><persistence passivation="false"><file-store/></persistence></replicated-cache>
