---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    openshift.io/description: {{ .Values.strimzi.namespaceName }}
    openshift.io/display-name: {{ .Values.strimzi.namespaceName }}
  name: {{ .Values.strimzi.namespaceName }}
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.strimzi.operatorGroupName }}
  namespace: {{ .Values.strimzi.namespaceName }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.strimzi.subscriptionName }}
  namespace: {{ .Values.strimzi.namespaceName }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: amqstreams.v2.8.0-0-0.1738265624.p
  source: redhat-operators
  sourceNamespace: openshift-marketplace