---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/description: {{ .Values.demo.namespaceName }}
    openshift.io/display-name: {{ .Values.demo.namespaceName }}
  name: {{ .Values.demo.namespaceName }}
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.strimzi.operatorGroupName }}
  namespace: {{ .Values.demo.namespaceName }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.strimzi.subscriptionName }}
  namespace: {{ .Values.demo.namespaceName }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: amq-streams
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: amqstreams.v2.8.0-0-0.1738265624.p  
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.datagrid.subscriptionName }}
  namespace: {{ .Values.demo.namespaceName }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: datagrid
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: datagrid-operator.v8.5.5  
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: pipelines-subscription
  namespace: {{ .Values.demo.namespaceName }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: pipelines-1.17
  installPlanApproval: Automatic
  name: pipelines
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: openshift-pipelines-operator-rh.v1.17.1    