apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: example-console
  namespace: appdev-streams
  annotations:
    argocd.argoproj.io/sync-wave: "4"      
spec:
  hostname: streams-console.{{ .Values.cluster.domain }}
  kafkaClusters:
    - credentials:
        kafkaUser:
          name: console-kafka-user1
      listener: plain
      name: my-cluster
      namespace: appdev-streams
