apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: correlationid-consumer-applications-cache
  namespace: {{ .Values.demo.namespaceName }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"  
spec:
  clusterName: example-infinispan
  name: correlationid-consumer-applications-cache
  template: |
    distributedCache: 
      owners: "2"
      mode: "SYNC"
      statistics: "true"
      encoding: 
        mediaType: "application/x-protostream"