apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-working-source
  namespace: {{ .Values.demo.namespaceName }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"      
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi