apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: response
  namespace: {{ .Values.demo.namespaceName }}  
  labels:
    strimzi.io/cluster: my-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "4"  
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824