apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: simplerun
  namespace: appdev-streams
  annotations:
    argocd.argoproj.io/sync-wave: "5"    
spec:
  params:
    - name: git-url
      value: 'https://github.com/sgutierr/rest2kafka.git'
    - name: git-revision
      value: main
    - name: sslVerify
      value: 'false'      
    - name: deleteExisting
      value: 'false'      
  pipelineRef:
    name: new-pipeline
  serviceAccountName: pipeline
  podTemplate:
    securityContext:
      fsGroup: 65532
  timeout: 1h0m0s
  workspaces:
    - name: my-working-source
      persistentVolumeClaim: 
        claimName: my-working-source
