apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: example-infinispan
  namespace: {{ .Values.demo.namespaceName }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
    service:
      type: DataGrid
    security:
      endpointAuthentication: false
      endpointSecretName: connect-secret 
      endpointEncryption:
        type: None
        clientCert: None
    replicas: 1
    expose:
      host: dg.{{ .Values.demo.namespaceName }}.apps.k8s.dev.local
      type: Route    
