kind: Secret
apiVersion: v1
metadata:
  name: kafka-user1-secret
  namespace: {{ .Values.demo.namespaceName }} 
  labels:
    app.kubernetes.io/instance: kafka-user1-secret
    app.kubernetes.io/managed-by: strimzi-user-operator
    app.kubernetes.io/name: strimzi-user-operator
    app.kubernetes.io/part-of: strimzi-kafka-user1-secret
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: KafkaUser
  annotations:
    argocd.argoproj.io/sync-wave: "3"      
data:
  user1pass: SEl3VEh5aTZ2OXp0V0dKU2hhZDdzR0dnSDFPa1FUcW4=
  sasl.jaas.config: b3JnLmFwYWNoZS5rYWZrYS5jb21tb24uc2VjdXJpdHkuc2NyYW0uU2NyYW1Mb2dpbk1vZHVsZSByZXF1aXJlZCB1c2VybmFtZT0iY29uc29sZS1rYWZrYS11c2VyMSIgcGFzc3dvcmQ9IkhJd1RIeWk2djl6dFdHSlNoYWQ3c0dHZ0gxT2tRVHFuIjs=
type: Opaque